[workspace]
resolver = "2"
members = [
    "crates/sqns-core",
    "crates/sqns-client",
    "crates/sqnsd",
    "crates/sqns",
]

[workspace.package]
version = "0.2.2"
edition = "2024"
license = "MIT"

[workspace.dependencies]
squic = { git = "https://github.com/wave-cl/squic-rust", tag = "v0.13.1" }
sqns-core = { path = "crates/sqns-core" }
sqns-client = { path = "crates/sqns-client", default-features = false }
tokio = { version = "1", features = ["full"] }
quinn = "0.11"
clap = { version = "4", features = ["derive"] }
ed25519-dalek = { version = "2", features = ["rand_core"] }
bs58 = "0.5"
dirs = "6"
hex = "0.4"
libc = "0.2"
rand = "0.9"
rand_core = { version = "0.6", features = ["getrandom"] }
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
tempfile = "3"
hickory-resolver = { version = "0.26", default-features = false, features = ["dnssec-ring", "system-config", "tokio"] }

[profile.release]
lto = true
codegen-units = 1
strip = true
